project:
  type: website
  output-dir: docs
  
website:
  title: "Demo site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - MOM_manuscript.qmd
      - MOM_Religiosity_MS.qmd
      
format: html
      